# Generated by Django 4.2.5 on 2023-09-12 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_doctor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="DailyTimeSlots",
            fields=[
                (
                    "daily_timeslots_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("appointment_date", models.DateField()),
                ("time_slots", models.JSONField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.doctor"
                    ),
                ),
            ],
        ),
    ]
