# Generated by Django 4.2.5 on 2023-09-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_doctor_user_dailytimeslots"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("appointment_purpose", models.TextField()),
                ("availability", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.patient"
                    ),
                ),
            ],
        ),
    ]
