# Generated by Django 4.2.4 on 2023-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
