# Generated by Django 4.2.4 on 2023-09-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
